question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "Nintendo started out as a playing card manufacturer.", "answer": "True", },
    {"text": "The Ace Attorney trilogy was suppose to end with Phoenix Wright: Ace Attorney &minus; Trials and Tribulations as its final game.", "answer": "True"},
    {"text": "In World of Warcraft lore, Thrall is the original wielder of Doomhammer.", "answer": "False"},
    {"text": "The Sniper's SMG in Team Fortress 2, was originally intended to be the Scout's primary weapon.", "answer": "True"},
    {"text": "Resident Evil 4 was originally meant to be a Nintendo GameCube exclusive.", "answer": "True", },
    {"text": "In Starbound, the track played by the Decorated Music Box is named Atlas.", "answer": "True"},
    {"text": "In Call Of Duty: Zombies, you can upgrade the Apothicon Servant in the Shadows Of Evil map.", "answer": "False"},
    {"text": "The Fiat Multipla is a drivable car in Forza Horizon 3.", "answer": "False", },
    {"text": "In League of Legends, there exists four different types of Dragon.", "answer": "False"},
    {"text": "The game Garry's Mod originally took assets and codes from the popular Half Life 2 mod JBmod.", "answer": "True"}
]